# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "vendor/**/*"
    - "script/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/**/*"
  Include:
    - "**/*.rb"

  UseCache: false
  NewCops: enable
  TargetRubyVersion: 3.4.*

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
