services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - ./storage:/rails/storage
      - ./log:/rails/log
    restart: unless-stopped
    env_file:
      - .env
